# Dockerfile.dev
FROM node:20-alpine

# Define o diretório de trabalho
WORKDIR /usr/src/app

# Copia o package.json e yarn.lock
COPY package.json yarn.lock ./

# Instala as dependências (incluindo devDependencies)
RUN yarn install --frozen-lockfile

# Copia o restante do código
COPY . .

# Expõe a porta 3001 (pode ajustar se precisar)
EXPOSE 3001

# Inicia a aplicação em modo desenvolvimento (hot reload)
CMD ["yarn", "start:dev"]
