name: Backend CI

# Executa em push ou pull-request para as branches desejadas
on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build-and-test:
    name: 🛠 Build • Lint • Test
    runs-on: ubuntu-latest

    steps:
      # 1) Faz checkout do código
      - uses: actions/checkout@v3

      # 2) Prepara Node 20
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: yarn

      # 3) Instala dependências
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 4) Lint
      - name: Lint
        run: yarn lint

      # 5) Testes com cobertura
      - name: Run tests
        run: yarn test:cov
